/**
 * Build the chapter/verse-count index from the bundled scripture XML.
 *
 * Only *counts* are extracted — how many chapters each book has and how many
 * verses each chapter has. No scripture text is copied into this repo's source
 * output, which keeps the index usable regardless of how the Biblica permission
 * request lands (see the licensing gate in docs/SPEC.txt).
 *
 * Both translations are indexed and compared: where they disagree on a verse
 * count, the reference validator has to be lenient, so the disagreements are
 * recorded rather than silently averaged away.
 *
 *   pnpm --filter @abide/content build:verse-index
 */
import { createReadStream } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import { createInterface } from 'node:readline'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const here = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(here, '../../..')

type Counts = Record<string, number[]>

/**
 * The files are ~5 MB of one-element-per-line XML. A streaming line scan avoids
 * holding the whole DOM — and the whole scripture text — in memory at once.
 */
async function indexFile(file: string): Promise<Counts> {
  const counts: Counts = {}
  let book = 0
  let chapter = 0
  let verses = 0

  const flushChapter = () => {
    if (book > 0 && chapter > 0) {
      const list = (counts[String(book)] ??= [])
      list[chapter - 1] = verses
    }
  }

  const rl = createInterface({
    input: createReadStream(file, { encoding: 'utf8' }),
    crlfDelay: Infinity,
  })

  for await (const line of rl) {
    for (const m of line.matchAll(/<(book|chapter|verse)\b[^>]*number="(\d+)"/g)) {
      const tag = m[1]
      const n = Number(m[2])
      if (tag === 'book') {
        flushChapter()
        book = n
        chapter = 0
        verses = 0
      } else if (tag === 'chapter') {
        flushChapter()
        chapter = n
        verses = 0
      } else {
        verses = Math.max(verses, n)
      }
    }
  }
  flushChapter()
  return counts
}

const amharic = await indexFile(path.join(repoRoot, 'bibles/AmharicNASVBible.xml'))
const english = await indexFile(path.join(repoRoot, 'bibles/EnglishNIVBible.xml'))

const disagreements: string[] = []
for (const book of Object.keys(amharic)) {
  const am = amharic[book] ?? []
  const en = english[book] ?? []
  if (am.length !== en.length) {
    disagreements.push(`book ${book}: ${am.length} chapters (am) vs ${en.length} (en)`)
    continue
  }
  am.forEach((count, i) => {
    if (en[i] !== count) disagreements.push(`book ${book} ch ${i + 1}: ${count} (am) vs ${en[i]} (en)`)
  })
}

// The validator accepts a reference valid in *either* translation. A reader in one
// language must never be told the ministry's reference is broken because the other
// language's versification splits a verse differently.
const merged: Counts = {}
for (const book of Object.keys(amharic)) {
  const am = amharic[book] ?? []
  const en = english[book] ?? []
  const chapters = Math.max(am.length, en.length)
  merged[book] = Array.from({ length: chapters }, (_, i) =>
    Math.max(am[i] ?? 0, en[i] ?? 0),
  )
}

const out = path.join(here, '../data/verse-counts.json')
await writeFile(
  out,
  JSON.stringify(
    {
      note: 'Generated by scripts/build-verse-index.ts. Counts only, no scripture text.',
      generatedAt: new Date().toISOString().slice(0, 10),
      disagreements,
      counts: merged,
    },
    null,
    1,
  ) + '\n',
  'utf8',
)

console.log(`indexed ${Object.keys(merged).length} books -> ${path.relative(repoRoot, out)}`)
console.log(`${disagreements.length} versification disagreements between the two texts`)
for (const d of disagreements.slice(0, 10)) console.log('  ' + d)
