/**
 * Parse and validate every reference in the ministry's devotion JSONs, and write a
 * report of everything a human has to decide about.
 *
 * This is the pre-commit check the Phase 5 import UI will run in the browser: same
 * parser, same validator, same report. Nothing is corrected here — a suggestion is
 * recorded and the reference is imported as written.
 *
 *   pnpm --filter @abide/content validate
 */
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { formatRef } from '../src/validate.ts'
import { prepareBundle, type ContentIssue, type SourceBundle } from '../src/import.ts'

const here = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(here, '../../..')

export const SOURCE_FILES = [
  'book_01_ruth_localized.json',
  'book_02_psalms_localized.json',
  'book_03_1st_timothy_localized.json',
]

export async function loadAll() {
  const books = []
  const issues: ContentIssue[] = []
  let sequence = 0
  let metadata: SourceBundle['devotional_metadata'] | null = null

  for (const file of SOURCE_FILES) {
    const bundle = JSON.parse(
      await readFile(path.join(repoRoot, file), 'utf8'),
    ) as SourceBundle
    metadata ??= bundle.devotional_metadata
    const prepared = prepareBundle(bundle, sequence)
    sequence += prepared.books.length
    books.push(...prepared.books)
    issues.push(...prepared.issues)
  }

  return { books, issues, metadata: metadata! }
}

if (import.meta.filename === process.argv[1]) {
  const { books, issues } = await loadAll()

  const totalRefs = books.reduce(
    (n, b) =>
      n +
      b.days.reduce(
        (m, d) => m + (d.passage ? 1 : 0) + d.keyVerses.length + d.crossRefs.length,
        0,
      ),
    0,
  )
  const devotionDays = books.reduce(
    (n, b) => n + b.days.filter((d) => d.kind === 'devotion').length,
    0,
  )

  const lines: string[] = []
  lines.push('# Scripture reference report')
  lines.push('')
  lines.push(`Generated by \`pnpm --filter @abide/content validate\`.`)
  lines.push('')
  lines.push(
    `${books.length} books · ${devotionDays} devotion days + ${books.length} summary days ` +
      `= **${devotionDays + books.length} scheduled days** · ${totalRefs} references parsed · ` +
      `**${issues.length} need a decision**.`,
  )
  lines.push('')

  if (issues.length === 0) {
    lines.push('No issues.')
  } else {
    lines.push('| Book | Day | Field | As written | Problem | Suggested |')
    lines.push('|---|---|---|---|---|---|')
    for (const i of issues) {
      lines.push(
        `| ${i.book} | ${i.day} | \`${i.field}\` | \`${i.raw}\` | ${i.message} | ${
          i.suggestion ? `\`${i.suggestion}\`` : '—'
        } |`,
      )
    }
  }

  lines.push('')
  lines.push('## Days with no passage')
  const noPassage = books.flatMap((b) =>
    b.days.filter((d) => d.kind === 'devotion' && !d.passage).map((d) => `${b.sourceId} day ${d.dayNumber}`),
  )
  lines.push(noPassage.length ? noPassage.map((s) => `- ${s}`).join('\n') : 'None.')
  lines.push('')

  const out = path.join(repoRoot, 'docs/content-report.md')
  await writeFile(out, lines.join('\n'), 'utf8')

  console.log(`${totalRefs} references parsed across ${devotionDays + books.length} days`)
  console.log(`${issues.length} issues -> ${path.relative(repoRoot, out)}`)
  for (const i of issues) {
    console.log(
      `  ${i.book} day ${i.day} ${i.field}: ${i.message}` +
        (i.suggestion ? `  -> ${i.suggestion}` : ''),
    )
  }

  // A sanity line that would have caught the inheritance bug: show what the
  // chained Luke reference actually resolved to.
  const tim = books.find((b) => b.sourceId === 'BOOK 03')
  const day8 = tim?.days.find((d) => d.dayNumber === 8)
  if (day8) {
    console.log(`\n1 Timothy day 8 cross-references resolved to:`)
    for (const r of day8.crossRefs) console.log('  ' + formatRef(r))
  }
}
